version: "2"
services:
  public:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/www
      - /www/node_modules
    tty: true
    environment:
      - PORT=9000
  mongo:
    image: mongo
    ports:
      - "29017:27017"
    command: --auth
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - ./data/db:/data/db