version: "2"
services:
  public:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/www
      - /www/node_modules
    tty: true
    expose:
      -"8080"
    environment:
      - PORT=8080
      - VIRTUAL_HOST=slumpsy.com
  mongo:
    image: mongo
    ports:
      - "29017:27017"
    command: --auth
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - ./data/db:/data/db
