version: "2"
services:
  public:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/www
    tty: true
    environment:
      - PORT=8080
  mongo:
    image: mongo
    ports:
      - "29017:27017"
    command: --auth
    volumes_from:
      - mongodata
  mongodata:
    image: tianon/true
    volumes:
      - ./data/db:/data/db